FIND_PATH(MONGOC_INCLUDE_DIR mongoc.h
        /usr/include/libmongoc-1.0
        /usr/local/include/libmongoc-1.0
        )

SET(MONGOC_NAMES ${MONGOC_NAMES} mongoc-1.0)
FIND_LIBRARY(MONGOC_LIBRARY
        NAMES ${MONGOC_NAMES}
        PATHS /usr/lib /usr/local/lib
        )

IF (MONGOC_LIBRARY AND MONGOC_INCLUDE_DIR)
    SET(MONGOC_LIBRARIES ${MONGOC_LIBRARY})
    SET(MONGOC_FOUND "YES")
ELSE (MONGOC_LIBRARY AND MONGOC_INCLUDE_DIR)
    SET(APR_FOUND "NO")
ENDIF (MONGOC_LIBRARY AND MONGOC_INCLUDE_DIR)


IF (MONGOC_FOUND)
    IF (NOT MONGOC_FIND_QUIETLY)
        MESSAGE(STATUS "Found MONGOC: ${MONGOC_LIBRARIES}")
    ENDIF (NOT MONGOC_FIND_QUIETLY)
ELSE (MONGOC_FOUND)
    IF (MONGOC_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find MONGOC library")
    ENDIF (MONGOC_FIND_REQUIRED)
ENDIF (MONGOC_FOUND)
